"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useCart } from "@/components/cart/CartProvider";
import { naira } from "@/lib/utils";

export default function Checkout(){const {items,total,clear}=useCart();const [f,setF]=useState({shippingName:"",shippingPhone:"",shippingEmail:"",address:"",city:"",state:""});const [paymentMethod,setPaymentMethod]=useState<"OPAY"|"WHATSAPP">("OPAY");const [error,setError]=useState("");const [checkingAccount,setCheckingAccount]=useState(true);const [submitting,setSubmitting]=useState(false);const [loggedIn,setLoggedIn]=useState(false);const router=useRouter();
useEffect(()=>{fetch("/api/me",{cache:"no-store"}).then(response=>response.json()).then(data=>setLoggedIn(Boolean(data.session))).catch(()=>setLoggedIn(false)).finally(()=>setCheckingAccount(false));},[]);
async function submit(e:React.FormEvent){e.preventDefault();setError("");setSubmitting(true);try{if(paymentMethod==="WHATSAPP"){const productLines=items.map((item:any)=>`${item.name} x ${item.quantity}`).join("\n");const message=encodeURIComponent(`Hello PaulTech Store, I would like to place an order.\n\nProducts:\n${productLines}\n\nExact total: ${naira(total)}\nName: ${f.shippingName}\nPhone: ${f.shippingPhone}\nEmail: ${f.shippingEmail}\nDelivery address: ${f.address}, ${f.city}, ${f.state}`);window.location.href=`https://wa.me/2348086394208?text=${message}`;return;}const r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:items.map((i:any)=>({productId:i.id,quantity:i.quantity})),paymentMethod,...f})});const d=await r.json();if(!r.ok){setError(d.error||"Checkout failed");return;}clear();router.push(`/order-success?orderId=${d.orderId}&method=opay`);}catch{setError("Unable to connect. Please try again.");}finally{setSubmitting(false);}}
if(!items.length)return <section className="container py-20 text-center">Your cart is empty.</section>;
if(checkingAccount)return <section className="container py-20 text-center"><p className="text-slate-500">Checking your account...</p></section>;
if(!loggedIn)return <section className="container flex min-h-[60vh] items-center justify-center py-12"><div className="w-full max-w-lg rounded-2xl border bg-white p-8 text-center shadow-sm"><h1 className="text-3xl font-black">Create an account to order</h1><p className="mt-3 text-slate-600">A PaulTech Store account is required to place and track your orders securely.</p><div className="mt-6 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/register?next=/checkout" className="rounded-xl bg-blue-600 px-6 py-3 font-bold text-white">Create account</Link><Link href="/login?next=/checkout" className="rounded-xl border px-6 py-3 font-bold text-blue-700">Sign in</Link></div></div></section>;
return <section className="container py-12"><h1 className="text-4xl font-black">Checkout</h1><form onSubmit={submit} className="mt-8 grid gap-8 lg:grid-cols-[1fr_360px]"><div className="rounded-2xl border bg-white p-6">{error&&<p role="alert" className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{Object.entries(f).map(([k,v])=><input key={k} required className="mt-3 w-full rounded-xl border p-3" placeholder={k.replace("shipping","").replace(/([A-Z])/g," $1")} type={k==="shippingEmail"?"email":"text"} value={v} onChange={e=>setF({...f,[k]:e.target.value})}/>) }<fieldset className="mt-6"><legend className="font-bold">How would you like to order?</legend><label className={`mt-3 flex cursor-pointer items-start gap-3 rounded-xl border p-4 ${paymentMethod==="OPAY"?"border-blue-600 bg-blue-50":""}`}><input type="radio" name="paymentMethod" value="OPAY" checked={paymentMethod==="OPAY"} onChange={()=>setPaymentMethod("OPAY")} className="mt-1"/><span><b>Transfer to OPay</b><small className="mt-1 block text-slate-500">Pay the exact total to our OPay account after placing your order.</small></span></label><label className={`mt-3 flex cursor-pointer items-start gap-3 rounded-xl border p-4 ${paymentMethod==="WHATSAPP"?"border-blue-600 bg-blue-50":""}`}><input type="radio" name="paymentMethod" value="WHATSAPP" checked={paymentMethod==="WHATSAPP"} onChange={()=>setPaymentMethod("WHATSAPP")} className="mt-1"/><span><b>Order through WhatsApp</b><small className="mt-1 block text-slate-500">Send your order details directly to PaulTech Store.</small></span></label></fieldset><button disabled={submitting} className="mt-5 w-full rounded-xl bg-blue-600 p-4 font-bold text-white disabled:cursor-not-allowed disabled:opacity-60">{submitting?"Opening...":paymentMethod==="OPAY"?"Place order and view OPay details":"Continue to WhatsApp"}</button></div><aside className="h-fit rounded-2xl border bg-white p-6"><h2 className="font-bold">Order total</h2><p className="mt-4 text-2xl font-black">{naira(total)}</p>{paymentMethod==="OPAY"&&<div className="mt-5 rounded-xl bg-blue-50 p-4 text-sm text-blue-950"><p className="font-bold">OPay transfer total</p><p className="mt-1 text-2xl font-black">{naira(total)}</p><p className="mt-2">You will receive the account details and order reference on the next screen.</p></div>}{paymentMethod==="WHATSAPP"&&<div className="mt-5 rounded-xl bg-green-50 p-4 text-sm text-green-950"><p className="font-bold">Direct WhatsApp order</p><p className="mt-2">Your product list, delivery details, and exact total will be sent to our WhatsApp DM.</p></div>}</aside></form></section>}
