[build]
  command = "npx prisma db push && npm run db:seed && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[context.production.environment]
  NEXT_PUBLIC_SITE_URL = "https://paultechstores.com.ng"