services:
  - type: web
    name: paultech-store
    runtime: node
    plan: free
    buildCommand: npm ci && npx prisma generate && npx prisma db push && npm run db:seed && npm run build
    startCommand: npx prisma db push && npm run db:seed && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: DATABASE_URL
        value: file:/opt/render/project/src/prisma/production.db
      - key: AUTH_SECRET
        sync: false
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: AUTH_EMAIL_FROM
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
